# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.det_sympd_C <- function(x, Log = FALSE) {
    .Call('_ztools_det_sympd', PACKAGE = 'ztools', x, Log)
}

.Mahalanobis_C <- function(x, center, covprec, is_prec) {
    .Call('_ztools_Mahalanobis', PACKAGE = 'ztools', x, center, covprec, is_prec)
}

.dmnorm_C <- function(x, mu, covprec, is_prec, unnorm = FALSE, log = FALSE) {
    .Call('_ztools_dmnorm', PACKAGE = 'ztools', x, mu, covprec, is_prec, unnorm, log)
}

.rmnorm_C <- function(z, mu, covprec, is_prec) {
    .Call('_ztools_rmnorm', PACKAGE = 'ztools', z, mu, covprec, is_prec)
}

