# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Mahalanobis <- function(x, center, covprec, is_prec) {
    .Call(`_ztools_Mahalanobis`, x, center, covprec, is_prec)
}

dmnorm <- function(x, mu, covprec, is_prec, unnorm = FALSE, log = FALSE) {
    .Call(`_ztools_dmnorm`, x, mu, covprec, is_prec, unnorm, log)
}

