# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.det_sympd_C <- function(x, Log = FALSE) {
    .Call('_ztools_det_sympd', PACKAGE = 'ztools', x, Log)
}

.Mahalanobis_C <- function(x, center, covprec, is_prec) {
    .Call('_ztools_Mahalanobis', PACKAGE = 'ztools', x, center, covprec, is_prec)
}

.dmnorm_C <- function(x, mu, covprec, is_prec, unnorm = FALSE, log = FALSE) {
    .Call('_ztools_dmnorm', PACKAGE = 'ztools', x, mu, covprec, is_prec, unnorm, log)
}

.rmnorm_C <- function(z, mu, covprec, is_prec) {
    .Call('_ztools_rmnorm', PACKAGE = 'ztools', z, mu, covprec, is_prec)
}

.update_nn_C <- function(z, y, X, mu, Sig, inv_Sig, V, inv_V) {
    .Call('_ztools_update_nn', PACKAGE = 'ztools', z, y, X, mu, Sig, inv_Sig, V, inv_V)
}

.update_gp_mean_C <- function(y, mu1, mu2, R12, R22) {
    .Call('_ztools_update_gp_mean', PACKAGE = 'ztools', y, mu1, mu2, R12, R22)
}

.update_gp_var_C <- function(R11, R12, R22) {
    .Call('_ztools_update_gp_var', PACKAGE = 'ztools', R11, R12, R22)
}

